### ISSUE TITLE
Able to get to top of nether roof

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#126]
![image](https://user-images.githubusercontent.com/11621666/136664604-d7a15689-57f3-4b42-bce7-62b291e91bb2.png)
![image](https://user-images.githubusercontent.com/11621666/136664597-947249b0-2ec7-4873-ae33-5dd67f8cfa62.png)

**Comment by Diec0** [comment]
Nah nah nah the screenshots are fake, remove this from issue ☹️

**Comment by drewdorris** [comment]
Fixed
