### ISSUE TITLE
Implement an AFK kick

### ISSUE THREAD

**Issue by dextonanderson** [Ruinscraft/mcatlas-issues#13]
Ensure people dont get kicked for things such as:
Walking less than one block
Using fishing rods
Mining a block
Planting or harvesting a crop
Traveling by minecart
Jumping

**Comment by drewdorris** [comment]
It'd be safe if we just checked for changes in yaw/pitch probably

**Comment by dextonanderson** [comment]
Timer should prob be 20-30 minutes, I like to be able to eat a meal, etc without getting kicked
