### ISSUE TITLE
Ability to disable global chat

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#16]

**Comment by dextonanderson** [comment]
Ensure this can be done with ruinscraft-chat the command /chat

**Comment by bomba1749** [comment]
y this critical but no fix 1.5 years later?!?!?!?!?!??!?!?!?!?!?!?!?!?!!?!??!!?!?!?!?!?!?! ????????????????????????????????????????????????????????????????? FIX PLS
