### ISSUE TITLE
Lockette issues

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#18]
- [x] Prevent users from being able to place locks anywhere (change PlayerInteractEvent handler to HIGHEST)
- [x] Write `[Town]` to allow an entire town to access a chest
- [x] Prevent locking in wilderness
- [x] Fix minecart hopper issue
- [x] Allow town owners/assistants to destroy locks?
- [x] Allow destroying of "Expired" signs

**Comment by dextonanderson** [comment]
This seem important, maybe we need to fork LockettePro

**Comment by dextonanderson** [comment]
@drewdorris link to the LockettePro fork we use please. we need to make a fork of the fork of the fork

**Comment by drewdorris** [comment]
https://github.com/NyaaCat/LockettePro

**Comment by dextonanderson** [comment]
This would be a towny issue, not a lockettepro issue actually. All lockettepro should need to do is return if the PlayerInteractEvent was cancelled (which it should get canceled by towny). The priorities are correct, towny is HIGH and lockettepro is NORMAL.

**Comment by drewdorris** [comment]
I think you have your priorities reversed @dextonanderson, lockettepro would execute before towny. Should this be a townyfork issue? Maybe check worldguard api in lockettepro to see if user is able to build

**Comment by dextonanderson** [comment]
negative, I believe I was correct

**Comment by drewdorris** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/EventPriority.html NORMAL executes before HIGH, so when Towny sees it it wouldn't have been cancelled?

**Comment by drewdorris** [comment]
Fixes implemented here https://github.com/Ruinscraft/LockettePro
