### ISSUE TITLE
Occasional kicks

### ISSUE THREAD

**Issue by dextonanderson** [Ruinscraft/mcatlas-issues#20]
https://i.imgur.com/BwuVmgs.png

**Comment by dextonanderson** [comment]
This should be fixed

**Comment by drewdorris** [comment]
Still an issue

**Comment by dextonanderson** [comment]
I think its related to viaversion but am not sure

**Comment by drewdorris** [comment]
Generally happens to me after teleporting, not sure if it just happens randomly

**Comment by Shadowbanisher** [comment]
I think it is either the authentication or maybe poor connection because I have ran in to this problem a lot with it telling me that I was remotely disconnected because of a Java exception

**Comment by dextonanderson** [comment]
Its either:
A viaversion issue

Or:
A plugin sending packets improperly and getting caught by Bungee. Eg https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/Varint21FrameDecoder.java#L35

**Comment by Shadowbanisher** [comment]
That may be the issue, but how would we go about fixing it because I think that it is a server side patch that is require, unless there is a way to prevent it from throwing that exception on the client side

**Comment by dextonanderson** [comment]
I am going to try using ViaVersion on bungee instead of all of our Spigot servers. I have to change some stuff to passthrough the ping to mcatlas so it displays the version protocol correctly in the server list

**Comment by Shadowbanisher** [comment]
Okay and also if this helps anything I got the full exception that it throws

Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host

**Comment by dextonanderson** [comment]
yeah, sadly it doesn't tell me much

**Comment by Shadowbanisher** [comment]
I figure but it was worth a shot if it could help

**Comment by dextonanderson** [comment]
> 
> 
> I am going to try using ViaVersion on bungee instead of all of our Spigot servers. I have to change some stuff to passthrough the ping to mcatlas so it displays the version protocol correctly in the server list

I have done this. It is potentially fixed now

**Comment by dextonanderson** [comment]
Still happening

**Comment by Shadowbanisher** [comment]
I don't think so or I haven't ran in to the problem again so I guess it is.

Thanks for the help!!

**Comment by dextonanderson** [comment]
Should be fixed. Will reopen if not

**Comment by dextonanderson** [comment]
The root cause wasn't fixed but for now, see https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0045-Add-Configuration-to-allow-empty-packets.patch
