### ISSUE TITLE
Lockette claims can't be broken if the container owner leaves the town

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#21]

**Comment by dextonanderson** [comment]
Will have to fork LockettePro

**Comment by dextonanderson** [comment]
https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/event/PlayerLeaveTownEvent.java

**Comment by drewdorris** [comment]
Town owner can `/plot clear` and clear all signs in the plot
