### ISSUE TITLE
Random towny commands seem to not work for random people

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#24]
This is more appropriate for a Towny issue, but gonna post it here as it's an issue for us.

Couple examples:
* User couldn't get out of a nation because he "didn't have permission" even though he did
* User couldn't teleport to any town spawns, despite being able to
* Maybe more I'm forgetting

Not sure if these are multiple different issues or something coming out of the same issue

**Comment by dextonanderson** [comment]
Likely fixed the the latest version of towny I installed

**Comment by drewdorris** [comment]
The `/n leave` thing was probably our error with permissions, hoping the `town spawn` thing is fixed.
