### ISSUE TITLE
Animals sometimes disappearing after warping

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#26]

**Comment by dextonanderson** [comment]
This is probably just the low entity activation distance

**Comment by drewdorris** [comment]
I should've clarified tamed animals, which shouldn't disappear randomly and are permanent(?)

**Comment by dextonanderson** [comment]
Mobs despawn if there are too many in a small area now

**Comment by dextonanderson** [comment]
Tamed animals take priority over non tamed, however

**Comment by dextonanderson** [comment]
should be fixed
