### ISSUE TITLE
Fix lockette expiry

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#42]
LockettePro native expiry was a straight 2 week expiration after placement instead of a 2 week after user was last online expiration. Use the other plugin

**Comment by drewdorris** [comment]
[here](https://www.spigotmc.org/resources/inactive-lockette.25644/)

**Comment by dextonanderson** [comment]
So just install the other plugin and disable expiry in LockettePro. is that it?

**Comment by drewdorris** [comment]
expiry is disabled, just need to install it

**Comment by dextonanderson** [comment]
was this installed yet?

**Comment by drewdorris** [comment]
No, have not tested it, need to do that

**Comment by drewdorris** [comment]
Going to test a 1 day expiry on test server and see if it works

**Comment by dextonanderson** [comment]
Any progress on this?

**Comment by drewdorris** [comment]
Didn't post here, but I'm thinking about whether we need expiry or not. I was thinking that we could have signs not expire, but they will delete whenever the claim they're in is cleared, unclaimed, or the town it's in falls into ruin

**Comment by drewdorris** [comment]
merging into #50
