### ISSUE TITLE
Armor seems to only be able to get one enchantment from an enchantment table, while other items can get multiple enchantments

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#48]

**Comment by dextonanderson** [comment]
Potentially has to do with https://github.com/dextonanderson/Tissue/commit/90772ce8977a0fc7420cff6128b6a4d77ef7cf61#diff-1891aebae293ced5de7c9a5826f20c0aR15

**Comment by dextonanderson** [comment]
Confirmed it is. Looking into a solution

**Comment by dextonanderson** [comment]
Disregard last comment. I dont think this is an actual issue with further testing. I was able to obtain a normal array of enchantments whilst testing enchanting armor. Can anyone else rebut this?

**Comment by dextonanderson** [comment]
No one has rebutted. closing
