### ISSUE TITLE
List of the richest nations

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#49]
Combined wealth of all the towns + the nation, or just the nation? Maybe show both

**Comment by dextonanderson** [comment]
also see https://github.com/TownyAdvanced/Towny/issues/3174

**Comment by LlmDl** [comment]
Yeah this is done, the bank balance option is in 0.94.0.4, townblocks/online is added in 0.94.0.5

**Comment by dextonanderson** [comment]
@LlmDl Thanks, appreciate it

**Comment by dextonanderson** [comment]
Gonna close this, it will be implemented once we update towny.
