### ISSUE TITLE
Teleport timer cancels if PvP

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#55]

**Comment by dextonanderson** [comment]
I think if we suggested this to the towny team, they'd implement it as a configuration option probably

**Comment by drewdorris** [comment]
I think this might be a thing. need to test

**Comment by ds58** [comment]
https://github.com/Ruinscraft/mcatlas-towny-helpers/commit/35553b7787c457fe4bbe48a4e230caf388e79882
