### ISSUE TITLE
Fork ChestShop

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#60]

**Comment by drewdorris** [comment]
Will PR this to upstream once added, but not sure if they want it. @dextonanderson post mcatlas-economy!!

**Comment by windows-virus** [comment]
Players have a personal bank, could use that for chestshops owners to receive gold and chestshops users to have gold taken away from them.

**Comment by drewdorris** [comment]
I'd rather not, as I don't want people to have gold in non-physical form (besides town and nation banks). They could put all their gold in the personal bank and keep it safe forever and ever. Would probably be easier to do that though

**Comment by windows-virus** [comment]
Might be a good idea to add a drawback to using a personal bank, for example 1 gold daily bank tax, forcing people to not hoard the money and instead only putting money into the bank whenever they want to buy something from chest shop?

**Comment by drewdorris** [comment]
In progress here https://github.com/Ruinscraft/DukesMart/tree/jianbriggs-init

**Comment by drewdorris** [comment]
Thanks Ian
