### ISSUE TITLE
Alternate recipe for concrete

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#77]
8 concrete powder with water bucket in the middle = concrete

**Comment by bomba1749** [comment]
when this is do?!?!?!??!?!?!?!?!?!??!?!?!?!?!?!??!?!?!?!

**Comment by ds58** [comment]
Adding to TODO #84 
@drewdorris

**Comment by drewdorris** [comment]
Merged with #73
