### ISSUE TITLE
PvP timer for /goto counts if you're damaged by anything

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-issues#81]

**Comment by ds58** [comment]
Are you saying add a timer? What do you mean

**Comment by drewdorris** [comment]
There is a timer for PvP already, it just triggers whenever any damage is done to the player, not just PvP. That is the problem

**Comment by Diec0** [comment]
Can players see the timer? That would be usful

**Comment by drewdorris** [comment]
This should be fixed
