### ISSUE TITLE
Some 1.14-1.16 blocks with inventories/menus can be opened in any town claim, even with switching off

### ISSUE THREAD

**Issue by ds58** [Ruinscraft/mcatlas-issues#92]

**Comment by drewdorris** [comment]
This was reported a few days ago but is it still an issue? I thought I fixed it

**Comment by ds58** [comment]
how was it fixed?

**Comment by drewdorris** [comment]
I didn't test if it was still an issue, but I added it to the list of blocks that need switch perms in Towny

**Comment by ds58** [comment]
okay yeah that would fix it then

**Comment by drewdorris** [comment]
Someone did report I believe smithing tables and some other 1.16 blocks still needing to have accessibility fixed. Will need to look into

**Comment by dextonanderson** [comment]
Added 
```
- BARREL
- SMOKER
- SMITHING_TABLE
```

to lockette "lockables" config section

eg: https://github.com/NyaaCat/LockettePro/blob/1.16/src/main/resources/config.yml#L35

**Comment by ds58** [comment]
Didn't we fix this already?

**Comment by drewdorris** [comment]
Added composters, everything should be added now
