### ISSUE TITLE
Barrels are not lockable with lockette

### ISSUE THREAD

**Issue by ds58** [Ruinscraft/mcatlas-issues#93]

**Comment by drewdorris** [comment]
Might include other 1.16 blocks (similar to #92)

**Comment by ds58** [comment]
Added 
```
- BARREL
- SMOKER
- SMITHING_TABLE
```

to lockette "lockables" config section

eg: https://github.com/NyaaCat/LockettePro/blob/1.16/src/main/resources/config.yml#L35
